[package]
name = "titanic"
version = "0.1.0"
edition = "2021"

[dependencies]
burn = { version = "0.14.0", features = ["autodiff", "wgpu"] }
csv = "1.3.0"
plotly = "0.9.0"
serde = { version = "1.0.209", features = ["derive"] }


